### PR TITLE
Work around to address build and lazy-loading issues.

### PR DESCRIPTION
**Pull request by dfbaskin**
Moves the output from the `packagr` builds to a `libs` directory under the main application project.  Also adds `System.import` functionality to work around AOT issue.

### CODE REVIEW

**Comment by dfbaskin** [comment]
Addresses Issues #1 and #2.

**Comment by yonigo** [comment]
Hey @dfbaskin,
I'm also using ng-packagr to bundle component-libraries for an angular-cli generated app.
While I'm able to use components from the bundle, I'm unable to lazy-load a feature-module.

Were you successful in lazy-loading npm packaged modules?

Thanks, yoni.

**Comment by dfbaskin** [comment]
I ended up just using a work-around.  I used `ng-packagr` to build the libraries into a path local to the project that is using them.  (This PR does that.)  Then the library lazy-loads fine.

**Comment by mnicic** [comment]
Well...in that case the **real npm library** is not lazy loaded. Actually, you got separate app chunk for your library which will be lazy loaded. Right?

**Pull request merged**
